
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: npm install -g firebase-tools
    - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting --non-interactive
